// AUTO-GENERATED by contractRenderer.ts — DO NOT EDIT
export const GAME_CONFIG = {
  targetRtpPct: 96.2,
  houseEdgePct: 3.8,
  freeSpinsCount: 18,
  freeSpinsCap: 50,
  freeSpinsMultiplier: 18,
  minBetBaseUnits: BigInt('10000'),
  maxBetBaseUnits: BigInt('1000000000000'),
  defaultBetDisplay: '1.00',
  halfMinGuard: BigInt('10000'),
} as const;

export const EMPTY_HEX = '0x' as const;
