// AUTO-GENERATED by contractRenderer.ts — DO NOT EDIT
// STUDIO PATCH: pays resolve from the active MATH profile (activeMath) — same
// re-stamp emulation as reels.ts, so decode-side evaluateWins pays what the
// active profile pays. Baked Fantasy pays stay the default.
import { SymbolId } from './symbols';
import { ACTIVE_MATH } from './activeMath';

export type PayEntry = [number, number, number];

const FANTASY_PAY_TABLE: Partial<Record<number, PayEntry>> = {
  [SymbolId.WILD]:   [182, 1274, 33375],
  [SymbolId.HIGH_A]: [182, 1274, 33375],
  [SymbolId.HIGH_B]: [76, 516, 13350],
  [SymbolId.MID_C]:  [0, 364, 6372],
  [SymbolId.MID_D]:  [0, 182, 2731],
  [SymbolId.LOW_E]:  [0, 0, 1153],
  [SymbolId.LOW_F]:  [0, 0, 0],
  [SymbolId.LOW_G]:  [0, 0, 0],
};

export const PAY_TABLE: Partial<Record<number, PayEntry>> =
  ACTIVE_MATH?.payTable ?? FANTASY_PAY_TABLE;

export const SCATTER_PAY: PayEntry = ACTIVE_MATH?.scatterPay ?? [40, 219, 1495];

export const MAX_WIN_MULTIPLIER = 5000;
export const BPS_DIVISOR = 10_000;
export const MIN_MATCHING_REELS = 3;

export { REEL_COUNT as TOTAL_REELS, VISIBLE_ROWS } from './reels';
