// AUTO-GENERATED by contractRenderer.ts — DO NOT EDIT
import { SymbolId } from './symbols';

export type PayEntry = [number, number, number];

export const PAY_TABLE: Partial<Record<number, PayEntry>> = {
  [SymbolId.WILD]:   [182, 1274, 33375],
  [SymbolId.HIGH_A]: [182, 1274, 33375],
  [SymbolId.HIGH_B]: [76, 516, 13350],
  [SymbolId.MID_C]:  [0, 364, 6372],
  [SymbolId.MID_D]:  [0, 182, 2731],
  [SymbolId.LOW_E]:  [0, 0, 1153],
  [SymbolId.LOW_F]:  [0, 0, 0],
  [SymbolId.LOW_G]:  [0, 0, 0],
};

export const SCATTER_PAY: PayEntry = [40, 219, 1495];

export const MAX_WIN_MULTIPLIER = 5000;
export const BPS_DIVISOR = 10_000;
export const MIN_MATCHING_REELS = 3;

export { REEL_COUNT as TOTAL_REELS, VISIBLE_ROWS } from './reels';
