// cellBackdropParams.ts — the nine adjustable-params for the per-symbol cell
// backdrop, in the same shape as your whitelist entries. Spread into
// ADJUSTABLE_PARAMS. Uses the 'color' type (see the reel-background handoff for
// the one <input type=color> renderer case; same type, reuse it).

export const CELL_BACKDROP_PARAMS = [
  {
    id: 'cellBgColor',
    label: 'Cell backdrop — colour',
    layer: 'canvas-layers',
    type: 'color',
    default: '#101018',
    description: 'Fill colour of the per-cell backdrop pocket behind each symbol — pick any RGB colour. Stays in sync with the cell-backdrop hue/saturation/brightness sliders. Phrases: "make the cell pockets dark / blue / purple".',
    keywords: ['cell', 'backdrop', 'pocket', 'tile', 'colour', 'color', 'rgb'],
  },
  {
    id: 'cellBgHue',
    label: 'Cell backdrop — hue',
    layer: 'canvas-layers',
    type: 'number',
    min: 0, max: 360, step: 1,
    default: 240,
    description: 'Colour (hue) of the per-cell backdrop pockets.',
    keywords: ['cell', 'backdrop', 'pocket', 'hue', 'colour', 'color'],
  },
  {
    id: 'cellBgSaturation',
    label: 'Cell backdrop — saturation',
    layer: 'canvas-layers',
    type: 'number',
    min: 0, max: 100, step: 1,
    default: 20,
    description: 'How colourful the per-cell backdrop pockets are (0 = grey, 100 = vivid).',
    keywords: ['cell', 'backdrop', 'saturation', 'grey', 'vivid'],
  },
  {
    id: 'cellBgLightness',
    label: 'Cell backdrop — brightness',
    layer: 'canvas-layers',
    type: 'number',
    min: 0, max: 100, step: 1,
    default: 8,
    description: 'Brightness of the per-cell backdrop pockets (0 = near-black, 100 = white).',
    keywords: ['cell', 'backdrop', 'brightness', 'dark', 'light'],
  },
  {
    id: 'cellBgOpacity',
    label: 'Cell backdrop — opacity',
    layer: 'canvas-layers',
    type: 'number',
    min: 0, max: 100, step: 1,
    default: 45,
    description: 'How opaque the per-cell backdrop pockets are (0 = invisible, 100 = solid).',
    keywords: ['cell', 'backdrop', 'opacity', 'transparency', 'alpha'],
  },
  {
    id: 'cellBgRadius',
    label: 'Cell backdrop — corner radius',
    layer: 'canvas-layers',
    type: 'number',
    min: 0, max: 40, step: 1,
    default: 14,
    description: 'Corner rounding of the per-cell backdrop pockets in px (0 = square).',
    keywords: ['cell', 'backdrop', 'corner', 'radius', 'round', 'square'],
  },
  {
    id: 'cellBgInset',
    label: 'Cell backdrop — inset/gap',
    layer: 'canvas-layers',
    type: 'number',
    min: 0, max: 30, step: 1,
    default: 3,
    description: 'How far each pocket is inset from its cell edge in px = the gap between pockets.',
    keywords: ['cell', 'backdrop', 'inset', 'gap', 'padding', 'spacing'],
  },
  {
    id: 'cellBgBorderColor',
    label: 'Cell backdrop — border colour',
    layer: 'canvas-layers',
    type: 'color',
    default: '#ffffff',
    description: 'Outline colour of the per-cell backdrop pockets (only visible when border width > 0).',
    keywords: ['cell', 'backdrop', 'border', 'outline', 'stroke', 'colour', 'color'],
  },
  {
    id: 'cellBgBorderWidth',
    label: 'Cell backdrop — border width',
    layer: 'canvas-layers',
    type: 'number',
    min: 0, max: 8, step: 1,
    default: 0,
    description: 'Outline thickness of the per-cell backdrop pockets in px (0 = no border).',
    keywords: ['cell', 'backdrop', 'border', 'outline', 'stroke', 'width', 'thickness'],
  },
] as const;
